Repository JR-prog/Interlinked_SOEN390_Team11, pull requests merged in 2023-04, with the labels that each got.

#234 72 interlinked must be accessible on multiple screen sizes
  app/[locale]/admin/[uid]/page.tsx
  app/[locale]/admin/page.tsx
  app/[locale]/job-feed/page.tsx
  app/[locale]/notifications/page.tsx
  components/Buttons/NotificationDeleteButton/NotificationDeleteButton.tsx
  components/Buttons/ReportDeleteButton.tsx
  components/Icons/ReportBlueDot.tsx
  components/NavBar/NavBar.tsx
  components/Notification/CommentNotification/CommentNotification.tsx
  components/Notification/DmNotification/DmNotification.tsx
  components/Notification/JobNotification/JobNotification.tsx
  components/Notification/LikeNotification/LikeNotification.tsx
  components/Notification/LinkAcceptNotification/LinkAcceptNotification.tsx
  components/Notification/LinkRequestNotification/LinkRequestNotification.tsx
  components/Notification/NotificationHeader/NotificationHeader.tsx
  components/Notification/PostNotification/PostNotification.tsx
  components/Report/ReportHeader.tsx
  components/Report/ReportList.tsx
  components/Report/SingleReport.tsx
Labels: task

#220 131 create generic loading page component
  app/[locale]/DM/[uid]/page.tsx
  app/[locale]/DM/page.tsx
  app/[locale]/admin/[uid]/page.tsx
  app/[locale]/admin/lockedList/page.tsx
  app/[locale]/admin/page.tsx
  app/[locale]/feed/layout.tsx
  app/[locale]/feed/page.tsx
  app/[locale]/job-feed/page.tsx
  app/[locale]/login/page.tsx
  app/[locale]/manage-jobs/[jid]/page.tsx
  app/[locale]/manage-jobs/page.tsx
  app/[locale]/notifications/page.tsx
  app/[locale]/profile/[uid]/links/page.tsx
  app/[locale]/profile/[uid]/page.tsx
  app/[locale]/register/page.tsx
  components/Loading/Loading.tsx
  components/Loading/LoadingGif.gif
  components/Report/ReportList.tsx
  cypress/e2e/notification.cy.js
Labels: task

#233 189 generic account required page
  app/[locale]/DM/[uid]/page.tsx
  app/[locale]/account-required/layout.tsx
  app/[locale]/account-required/page.tsx
  app/[locale]/edit-profile/page.tsx
  app/[locale]/edit-profile/tests/edit-profile.test.tsx
  app/[locale]/feed/page.tsx
  app/[locale]/feed/tests/page.test.tsx
  app/[locale]/job-feed/page.tsx
  app/[locale]/manage-jobs/page.tsx
  app/[locale]/notifications/page.tsx
  app/[locale]/profile/page.tsx
  app/[locale]/profile/tests/Profile.test.tsx
  cypress/e2e/auth.cy.js
  translations/de.json
  translations/en.json
Labels: Refactor

#238 Various optimizations and date translation fixes
  app/[locale]/account-required/layout.tsx
  app/[locale]/account-required/page.tsx
  app/[locale]/feed/layout.tsx
  app/[locale]/feed/page.tsx
  app/[locale]/feed/tests/layout.test.tsx
  app/[locale]/head.tsx
  app/[locale]/job-feed/layout.tsx
  app/[locale]/job-feed/page.tsx
  app/[locale]/manage-jobs/layout.tsx
  app/[locale]/manage-jobs/page.tsx
  app/[locale]/profile/[uid]/links/page.tsx
  app/[locale]/profile/[uid]/links/tests/page.test.tsx
  app/[locale]/profile/[uid]/page.tsx
  app/[locale]/profile/page.tsx
  components/Card/FullPostCard.tsx
  components/Comment/CommentHeader.tsx
  components/DM/ChatroomCardHeader.tsx
  components/DM/MessageCard.tsx
  components/DM/TimeDivider.tsx
  components/Jobs/FullJobCard.tsx
  components/Jobs/JobPostBody.tsx
  components/Jobs/JobPostHeader.tsx
  components/Loading/Loading.tsx
  components/NavBar/NavBar.tsx
  components/Notification/NotificationHeader/NotificationHeader.tsx
  components/Post/PostHeader.tsx
  components/Report/ReportHeader.tsx
  components/Report/ReportList.tsx
  components/Report/ReportMessageCard.tsx
  config/locales.ts
  middleware.ts
Labels: Refactor

#242 v1.0.2 prod
  app/[locale]/account-required/page.tsx
  app/[locale]/admin/lockedList/page.tsx
  app/[locale]/job-feed/page.tsx
  app/[locale]/login/page.tsx
  app/[locale]/profile/[uid]/links/page.tsx
  app/[locale]/profile/[uid]/page.tsx
  components/Buttons/LinkButton/LinkButtonNoNumber.tsx
  components/Buttons/LinkButton/ViewLinkButton.tsx
  components/ProfilePage/ProfileProjects/ProfileProjects.tsx
  components/ProfilePage/ProfileProjects/tests/ProfileProjects.test.tsx
  contexts/AuthContext.tsx
  translations/de.json
  translations/en.json
  types/User.ts
Labels: release
